// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krwahbbojypmjuzklovh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyd2FoYmJvanlwbWp1emtsb3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDMwMzgsImV4cCI6MjA3NDQ3OTAzOH0.oNnE6_r8C0uMOBS6L6MQuQAHkerenD4Zq3tGdDzGc8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});